
export * from './lib/components';
export * from './lib/models';
export * from './lib/services';
export * from './lib/comunes.module';
//comunes hechas por viss
export * from './lib/components/input-field/input-field.module'
export * from './lib/components/form-template/form-template.module'
export * from './lib/components/domicilio-pasaporte-visa/domicilio-pasaporte-visa.module'
export * from './lib/components/subir-archivo/subir-archivo.module'
export * from './lib/components/datos-personales/datos-personales.module'
export * from './lib/components/tabs-view/tabs-view.module'
export * from './lib/components/form-datos-comun/form-datos-comun.module'
export * from './lib/components/table-view/table-view.module'
export * from './lib/components/form-requisitios/form-requisitios.module'
export * from './lib/components/mensaje-board/mensaje-board.module'
export * from './lib/components/mensaje-board-popup/mensaje-board-popup.module'
export * from './lib/components/table-view/table-view.module'
export * from './lib/components/datos-beneficiario-shared/datos-beneficiario-shared.module'
export * from './lib/components/datos-solicitante-shared/datos-solicitante-shared.module'
export * from './lib/components/multas/multas.module'